import type { IngredientCategory } from '@prisma/client'

type IngredientSeed = {
  name: string
  category: IngredientCategory
  typicalUnit: string
  estimatedCaloriesPerUnit?: number
  estimatedCostPerUnit?: number
}

type VariantGroup = {
  template: string
  variants: string[]
  category: IngredientCategory
  typicalUnit: string
}

const baseIngredients: IngredientSeed[] = [
  { name: 'apple', category: 'produce', typicalUnit: 'piece' },
  { name: 'banana', category: 'produce', typicalUnit: 'piece' },
  { name: 'orange', category: 'produce', typicalUnit: 'piece' },
  { name: 'lemon', category: 'produce', typicalUnit: 'piece' },
  { name: 'lime', category: 'produce', typicalUnit: 'piece' },
  { name: 'grapefruit', category: 'produce', typicalUnit: 'piece' },
  { name: 'tangerine', category: 'produce', typicalUnit: 'piece' },
  { name: 'clementine', category: 'produce', typicalUnit: 'piece' },
  { name: 'strawberry', category: 'produce', typicalUnit: 'g' },
  { name: 'blueberry', category: 'produce', typicalUnit: 'g' },
  { name: 'raspberry', category: 'produce', typicalUnit: 'g' },
  { name: 'blackberry', category: 'produce', typicalUnit: 'g' },
  { name: 'cranberry', category: 'produce', typicalUnit: 'g' },
  { name: 'grape', category: 'produce', typicalUnit: 'g' },
  { name: 'watermelon', category: 'produce', typicalUnit: 'piece' },
  { name: 'cantaloupe', category: 'produce', typicalUnit: 'piece' },
  { name: 'honeydew', category: 'produce', typicalUnit: 'piece' },
  { name: 'pineapple', category: 'produce', typicalUnit: 'piece' },
  { name: 'mango', category: 'produce', typicalUnit: 'piece' },
  { name: 'papaya', category: 'produce', typicalUnit: 'piece' },
  { name: 'kiwi', category: 'produce', typicalUnit: 'piece' },
  { name: 'pear', category: 'produce', typicalUnit: 'piece' },
  { name: 'peach', category: 'produce', typicalUnit: 'piece' },
  { name: 'nectarine', category: 'produce', typicalUnit: 'piece' },
  { name: 'plum', category: 'produce', typicalUnit: 'piece' },
  { name: 'apricot', category: 'produce', typicalUnit: 'piece' },
  { name: 'cherry', category: 'produce', typicalUnit: 'g' },
  { name: 'pomegranate', category: 'produce', typicalUnit: 'piece' },
  { name: 'fig', category: 'produce', typicalUnit: 'piece' },
  { name: 'date', category: 'produce', typicalUnit: 'g' },
  { name: 'coconut', category: 'produce', typicalUnit: 'piece' },
  { name: 'avocado', category: 'produce', typicalUnit: 'piece' },
  { name: 'tomatoes', category: 'produce', typicalUnit: 'piece' },
  { name: 'cucumber', category: 'produce', typicalUnit: 'piece' },
  { name: 'zucchini', category: 'produce', typicalUnit: 'piece' },
  { name: 'yellow squash', category: 'produce', typicalUnit: 'piece' },
  { name: 'eggplant', category: 'produce', typicalUnit: 'piece' },
  { name: 'carrot', category: 'produce', typicalUnit: 'piece' },
  { name: 'celery', category: 'produce', typicalUnit: 'stalk' },
  { name: 'onion', category: 'produce', typicalUnit: 'piece' },
  { name: 'garlic', category: 'produce', typicalUnit: 'clove' },
  { name: 'shallot', category: 'produce', typicalUnit: 'piece' },
  { name: 'scallion', category: 'produce', typicalUnit: 'stalk' },
  { name: 'leek', category: 'produce', typicalUnit: 'stalk' },
  { name: 'ginger', category: 'produce', typicalUnit: 'g' },
  { name: 'beet', category: 'produce', typicalUnit: 'piece' },
  { name: 'radish', category: 'produce', typicalUnit: 'piece' },
  { name: 'turnip', category: 'produce', typicalUnit: 'piece' },
  { name: 'parsnip', category: 'produce', typicalUnit: 'piece' },
  { name: 'potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'sweet potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'cauliflower', category: 'produce', typicalUnit: 'piece' },
  { name: 'broccoli', category: 'produce', typicalUnit: 'piece' },
  { name: 'cabbage', category: 'produce', typicalUnit: 'piece' },
  { name: 'kale', category: 'produce', typicalUnit: 'bunch' },
  { name: 'spinach', category: 'produce', typicalUnit: 'g' },
  { name: 'arugula', category: 'produce', typicalUnit: 'g' },
  { name: 'romaine lettuce', category: 'produce', typicalUnit: 'piece' },
  { name: 'iceberg lettuce', category: 'produce', typicalUnit: 'piece' },
  { name: 'butter lettuce', category: 'produce', typicalUnit: 'piece' },
  { name: 'bok choy', category: 'produce', typicalUnit: 'piece' },
  { name: 'swiss chard', category: 'produce', typicalUnit: 'bunch' },
  { name: 'collard greens', category: 'produce', typicalUnit: 'bunch' },
  { name: 'brussels sprouts', category: 'produce', typicalUnit: 'g' },
  { name: 'green beans', category: 'produce', typicalUnit: 'g' },
  { name: 'snap peas', category: 'produce', typicalUnit: 'g' },
  { name: 'peas', category: 'produce', typicalUnit: 'g' },
  { name: 'asparagus', category: 'produce', typicalUnit: 'bunch' },
  { name: 'artichoke', category: 'produce', typicalUnit: 'piece' },
  { name: 'corn', category: 'produce', typicalUnit: 'piece' },
  { name: 'mushroom', category: 'produce', typicalUnit: 'g' },
  { name: 'butternut squash', category: 'produce', typicalUnit: 'piece' },
  { name: 'acorn squash', category: 'produce', typicalUnit: 'piece' },
  { name: 'spaghetti squash', category: 'produce', typicalUnit: 'piece' },
  { name: 'pumpkin', category: 'produce', typicalUnit: 'piece' },
  { name: 'jalapeno', category: 'produce', typicalUnit: 'piece' },
  { name: 'serrano', category: 'produce', typicalUnit: 'piece' },
  { name: 'poblano', category: 'produce', typicalUnit: 'piece' },
  { name: 'habanero', category: 'produce', typicalUnit: 'piece' },
  { name: 'bell pepper', category: 'produce', typicalUnit: 'piece' },
  { name: 'basil', category: 'produce', typicalUnit: 'bunch' },
  { name: 'cilantro', category: 'produce', typicalUnit: 'bunch' },
  { name: 'parsley', category: 'produce', typicalUnit: 'bunch' },
  { name: 'dill', category: 'produce', typicalUnit: 'bunch' },
  { name: 'mint', category: 'produce', typicalUnit: 'bunch' },
  { name: 'thyme', category: 'produce', typicalUnit: 'bunch' },
  { name: 'rosemary', category: 'produce', typicalUnit: 'bunch' },
  { name: 'sage', category: 'produce', typicalUnit: 'bunch' },
  { name: 'oregano', category: 'produce', typicalUnit: 'bunch' },
  { name: 'chives', category: 'produce', typicalUnit: 'bunch' },
  { name: 'chicken breast', category: 'meat', typicalUnit: 'g' },
  { name: 'chicken thigh', category: 'meat', typicalUnit: 'g' },
  { name: 'chicken drumstick', category: 'meat', typicalUnit: 'g' },
  { name: 'chicken wing', category: 'meat', typicalUnit: 'g' },
  { name: 'whole chicken', category: 'meat', typicalUnit: 'g' },
  { name: 'ground beef', category: 'meat', typicalUnit: 'g' },
  { name: 'beef steak', category: 'meat', typicalUnit: 'g' },
  { name: 'beef roast', category: 'meat', typicalUnit: 'g' },
  { name: 'beef stew meat', category: 'meat', typicalUnit: 'g' },
  { name: 'ground pork', category: 'meat', typicalUnit: 'g' },
  { name: 'pork chops', category: 'meat', typicalUnit: 'g' },
  { name: 'pork tenderloin', category: 'meat', typicalUnit: 'g' },
  { name: 'pork shoulder', category: 'meat', typicalUnit: 'g' },
  { name: 'pork belly', category: 'meat', typicalUnit: 'g' },
  { name: 'bacon', category: 'meat', typicalUnit: 'g' },
  { name: 'ham', category: 'meat', typicalUnit: 'g' },
  { name: 'sausage', category: 'meat', typicalUnit: 'g' },
  { name: 'ground turkey', category: 'meat', typicalUnit: 'g' },
  { name: 'turkey breast', category: 'meat', typicalUnit: 'g' },
  { name: 'turkey sausage', category: 'meat', typicalUnit: 'g' },
  { name: 'lamb chops', category: 'meat', typicalUnit: 'g' },
  { name: 'ground lamb', category: 'meat', typicalUnit: 'g' },
  { name: 'veal cutlet', category: 'meat', typicalUnit: 'g' },
  { name: 'duck breast', category: 'meat', typicalUnit: 'g' },
  { name: 'salmon fillet', category: 'meat', typicalUnit: 'g' },
  { name: 'tuna steak', category: 'meat', typicalUnit: 'g' },
  { name: 'cod fillet', category: 'meat', typicalUnit: 'g' },
  { name: 'tilapia', category: 'meat', typicalUnit: 'g' },
  { name: 'haddock', category: 'meat', typicalUnit: 'g' },
  { name: 'halibut', category: 'meat', typicalUnit: 'g' },
  { name: 'trout', category: 'meat', typicalUnit: 'g' },
  { name: 'mahi mahi', category: 'meat', typicalUnit: 'g' },
  { name: 'swordfish', category: 'meat', typicalUnit: 'g' },
  { name: 'shrimp', category: 'meat', typicalUnit: 'g' },
  { name: 'scallops', category: 'meat', typicalUnit: 'g' },
  { name: 'crab', category: 'meat', typicalUnit: 'g' },
  { name: 'lobster', category: 'meat', typicalUnit: 'g' },
  { name: 'mussels', category: 'meat', typicalUnit: 'g' },
  { name: 'clams', category: 'meat', typicalUnit: 'g' },
  { name: 'oysters', category: 'meat', typicalUnit: 'g' },
  { name: 'sardines', category: 'pantry', typicalUnit: 'g' },
  { name: 'anchovies', category: 'pantry', typicalUnit: 'g' },
  { name: 'eggs', category: 'dairy', typicalUnit: 'piece' },
  { name: 'milk', category: 'dairy', typicalUnit: 'ml' },
  { name: 'butter', category: 'dairy', typicalUnit: 'tbsp' },
  { name: 'yogurt', category: 'dairy', typicalUnit: 'g' },
  { name: 'greek yogurt', category: 'dairy', typicalUnit: 'g' },
  { name: 'sour cream', category: 'dairy', typicalUnit: 'g' },
  { name: 'heavy cream', category: 'dairy', typicalUnit: 'ml' },
  { name: 'half and half', category: 'dairy', typicalUnit: 'ml' },
  { name: 'cream cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'cottage cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'ricotta', category: 'dairy', typicalUnit: 'g' },
  { name: 'cheddar cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'mozzarella cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'parmesan cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'feta cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'goat cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'blue cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'swiss cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'provolone cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'monterey jack cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'pepper jack cheese', category: 'dairy', typicalUnit: 'g' },
  { name: 'brie', category: 'dairy', typicalUnit: 'g' },
  { name: 'gouda', category: 'dairy', typicalUnit: 'g' },
  { name: 'ghee', category: 'dairy', typicalUnit: 'tbsp' },
  { name: 'tofu', category: 'perishable', typicalUnit: 'g' },
  { name: 'tempeh', category: 'perishable', typicalUnit: 'g' },
  { name: 'seitan', category: 'perishable', typicalUnit: 'g' },
  { name: 'almond milk', category: 'perishable', typicalUnit: 'ml' },
  { name: 'soy milk', category: 'perishable', typicalUnit: 'ml' },
  { name: 'oat milk', category: 'perishable', typicalUnit: 'ml' },
  { name: 'rice', category: 'pantry', typicalUnit: 'g' },
  { name: 'pasta', category: 'pantry', typicalUnit: 'g' },
  { name: 'flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'brown sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'powdered sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'baking powder', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'baking soda', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'yeast', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'oats', category: 'pantry', typicalUnit: 'g' },
  { name: 'quinoa', category: 'pantry', typicalUnit: 'g' },
  { name: 'barley', category: 'pantry', typicalUnit: 'g' },
  { name: 'couscous', category: 'pantry', typicalUnit: 'g' },
  { name: 'bulgur', category: 'pantry', typicalUnit: 'g' },
  { name: 'farro', category: 'pantry', typicalUnit: 'g' },
  { name: 'lentils', category: 'pantry', typicalUnit: 'g' },
  { name: 'split peas', category: 'pantry', typicalUnit: 'g' },
  { name: 'chickpeas', category: 'pantry', typicalUnit: 'g' },
  { name: 'black beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'kidney beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'pinto beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'navy beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'cannellini beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'great northern beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'refried beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'coconut milk', category: 'pantry', typicalUnit: 'ml' },
  { name: 'canned tomatoes', category: 'pantry', typicalUnit: 'g' },
  { name: 'tomato paste', category: 'pantry', typicalUnit: 'g' },
  { name: 'tomato sauce', category: 'pantry', typicalUnit: 'g' },
  { name: 'chicken stock', category: 'pantry', typicalUnit: 'ml' },
  { name: 'beef stock', category: 'pantry', typicalUnit: 'ml' },
  { name: 'vegetable stock', category: 'pantry', typicalUnit: 'ml' },
  { name: 'tortillas', category: 'pantry', typicalUnit: 'piece' },
  { name: 'bread', category: 'pantry', typicalUnit: 'slice' },
  { name: 'pita bread', category: 'pantry', typicalUnit: 'piece' },
  { name: 'naan', category: 'pantry', typicalUnit: 'piece' },
  { name: 'breadcrumbs', category: 'pantry', typicalUnit: 'g' },
  { name: 'cornmeal', category: 'pantry', typicalUnit: 'g' },
  { name: 'polenta', category: 'pantry', typicalUnit: 'g' },
  { name: 'crackers', category: 'pantry', typicalUnit: 'g' },
  { name: 'cereal', category: 'pantry', typicalUnit: 'g' },
  { name: 'granola', category: 'pantry', typicalUnit: 'g' },
  { name: 'peanut butter', category: 'pantry', typicalUnit: 'g' },
  { name: 'almond butter', category: 'pantry', typicalUnit: 'g' },
  { name: 'jam', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'honey', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'maple syrup', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'olive oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'vegetable oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'canola oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'avocado oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'coconut oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'sesame oil', category: 'staple', typicalUnit: 'tsp' },
  { name: 'white vinegar', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'apple cider vinegar', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'balsamic vinegar', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'red wine vinegar', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'rice vinegar', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'soy sauce', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'tamari', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'fish sauce', category: 'staple', typicalUnit: 'tsp' },
  { name: 'hot sauce', category: 'staple', typicalUnit: 'tsp' },
  { name: 'worcestershire sauce', category: 'staple', typicalUnit: 'tsp' },
  { name: 'mustard', category: 'staple', typicalUnit: 'tsp' },
  { name: 'dijon mustard', category: 'staple', typicalUnit: 'tsp' },
  { name: 'mayonnaise', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'ketchup', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'salsa', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'barbecue sauce', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'pesto', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'hummus', category: 'perishable', typicalUnit: 'tbsp' },
  { name: 'salt', category: 'staple', typicalUnit: 'tsp' },
  { name: 'black pepper', category: 'staple', typicalUnit: 'tsp' },
  { name: 'white pepper', category: 'staple', typicalUnit: 'tsp' },
  { name: 'garlic powder', category: 'staple', typicalUnit: 'tsp' },
  { name: 'onion powder', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cumin', category: 'staple', typicalUnit: 'tsp' },
  { name: 'chili powder', category: 'staple', typicalUnit: 'tsp' },
  { name: 'paprika', category: 'staple', typicalUnit: 'tsp' },
  { name: 'smoked paprika', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cayenne', category: 'staple', typicalUnit: 'tsp' },
  { name: 'turmeric', category: 'staple', typicalUnit: 'tsp' },
  { name: 'curry powder', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cinnamon', category: 'staple', typicalUnit: 'tsp' },
  { name: 'nutmeg', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cloves', category: 'staple', typicalUnit: 'tsp' },
  { name: 'allspice', category: 'staple', typicalUnit: 'tsp' },
  { name: 'ginger (ground)', category: 'staple', typicalUnit: 'tsp' },
  { name: 'coriander', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cardamom', category: 'staple', typicalUnit: 'tsp' },
  { name: 'bay leaves', category: 'staple', typicalUnit: 'piece' },
  { name: 'red pepper flakes', category: 'staple', typicalUnit: 'tsp' },
  { name: 'vanilla extract', category: 'staple', typicalUnit: 'tsp' },
  { name: 'almond extract', category: 'staple', typicalUnit: 'tsp' },
  { name: 'frozen peas', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen corn', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen spinach', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen broccoli', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen mixed vegetables', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen berries', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen strawberries', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen blueberries', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen pizza', category: 'frozen', typicalUnit: 'piece' },
  { name: 'frozen fries', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen chicken nuggets', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen fish sticks', category: 'frozen', typicalUnit: 'g' },
  { name: 'ice cream', category: 'frozen', typicalUnit: 'g' },
  { name: 'radicchio', category: 'produce', typicalUnit: 'piece' },
  { name: 'endive', category: 'produce', typicalUnit: 'piece' },
  { name: 'fennel', category: 'produce', typicalUnit: 'piece' },
  { name: 'celery root', category: 'produce', typicalUnit: 'piece' },
  { name: 'daikon', category: 'produce', typicalUnit: 'piece' },
  { name: 'jicama', category: 'produce', typicalUnit: 'piece' },
  { name: 'okra', category: 'produce', typicalUnit: 'g' },
  { name: 'watercress', category: 'produce', typicalUnit: 'bunch' },
  { name: 'mustard greens', category: 'produce', typicalUnit: 'bunch' },
  { name: 'dandelion greens', category: 'produce', typicalUnit: 'bunch' },
  { name: 'beet greens', category: 'produce', typicalUnit: 'bunch' },
  { name: 'kohlrabi', category: 'produce', typicalUnit: 'piece' },
  { name: 'rutabaga', category: 'produce', typicalUnit: 'piece' },
  { name: 'yam', category: 'produce', typicalUnit: 'piece' },
  { name: 'plantain', category: 'produce', typicalUnit: 'piece' },
  { name: 'passion fruit', category: 'produce', typicalUnit: 'piece' },
  { name: 'guava', category: 'produce', typicalUnit: 'piece' },
  { name: 'lychee', category: 'produce', typicalUnit: 'g' },
  { name: 'persimmon', category: 'produce', typicalUnit: 'piece' },
  { name: 'grapefruit juice', category: 'perishable', typicalUnit: 'ml' },
  { name: 'orange juice', category: 'perishable', typicalUnit: 'ml' },
  { name: 'apple juice', category: 'perishable', typicalUnit: 'ml' },
  { name: 'lemon juice', category: 'perishable', typicalUnit: 'ml' },
  { name: 'lime juice', category: 'perishable', typicalUnit: 'ml' },
  { name: 'tarragon', category: 'produce', typicalUnit: 'bunch' },
  { name: 'marjoram', category: 'produce', typicalUnit: 'bunch' },
  { name: 'lemongrass', category: 'produce', typicalUnit: 'stalk' },
  { name: 'ginger root', category: 'produce', typicalUnit: 'g' },
  { name: 'curry leaves', category: 'produce', typicalUnit: 'bunch' },
  { name: 'jalapeno peppers', category: 'produce', typicalUnit: 'piece' },
  { name: 'serrano peppers', category: 'produce', typicalUnit: 'piece' },
  { name: 'poblano peppers', category: 'produce', typicalUnit: 'piece' },
  { name: 'habanero peppers', category: 'produce', typicalUnit: 'piece' },
  { name: 'cilantro lime', category: 'produce', typicalUnit: 'bunch' },
  { name: 'romano beans', category: 'produce', typicalUnit: 'g' },
  { name: 'snap peas', category: 'produce', typicalUnit: 'g' },
  { name: 'snow peas', category: 'produce', typicalUnit: 'g' },
  { name: 'cherry tomatoes', category: 'produce', typicalUnit: 'g' },
  { name: 'grape tomatoes', category: 'produce', typicalUnit: 'g' },
  { name: 'roma tomatoes', category: 'produce', typicalUnit: 'g' },
  { name: 'heirloom tomatoes', category: 'produce', typicalUnit: 'g' },
  { name: 'red onion', category: 'produce', typicalUnit: 'piece' },
  { name: 'white onion', category: 'produce', typicalUnit: 'piece' },
  { name: 'yellow onion', category: 'produce', typicalUnit: 'piece' },
  { name: 'sweet onion', category: 'produce', typicalUnit: 'piece' },
  { name: 'russet potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'yukon gold potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'red potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'fingerling potato', category: 'produce', typicalUnit: 'piece' },
  { name: 'button mushrooms', category: 'produce', typicalUnit: 'g' },
  { name: 'cremini mushrooms', category: 'produce', typicalUnit: 'g' },
  { name: 'portobello mushrooms', category: 'produce', typicalUnit: 'g' },
  { name: 'shiitake mushrooms', category: 'produce', typicalUnit: 'g' },
  { name: 'oyster mushrooms', category: 'produce', typicalUnit: 'g' },
  { name: 'green apple', category: 'produce', typicalUnit: 'piece' },
  { name: 'red apple', category: 'produce', typicalUnit: 'piece' },
  { name: 'whole wheat bread', category: 'pantry', typicalUnit: 'slice' },
  { name: 'white bread', category: 'pantry', typicalUnit: 'slice' },
  { name: 'sourdough bread', category: 'pantry', typicalUnit: 'slice' },
  { name: 'rye bread', category: 'pantry', typicalUnit: 'slice' },
  { name: 'bagel', category: 'pantry', typicalUnit: 'piece' },
  { name: 'english muffin', category: 'pantry', typicalUnit: 'piece' },
  { name: 'baguette', category: 'pantry', typicalUnit: 'piece' },
  { name: 'corn tortillas', category: 'pantry', typicalUnit: 'piece' },
  { name: 'flour tortillas', category: 'pantry', typicalUnit: 'piece' },
  { name: 'ramen noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'rice noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'udon noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'soba noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'egg noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'instant noodles', category: 'pantry', typicalUnit: 'g' },
  { name: 'oat flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'almond flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'coconut flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'chickpea flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'corn starch', category: 'pantry', typicalUnit: 'g' },
  { name: 'tapioca starch', category: 'pantry', typicalUnit: 'g' },
  { name: 'potato starch', category: 'pantry', typicalUnit: 'g' },
  { name: 'baking chocolate', category: 'pantry', typicalUnit: 'g' },
  { name: 'chocolate chips', category: 'pantry', typicalUnit: 'g' },
  { name: 'cocoa powder', category: 'pantry', typicalUnit: 'g' },
  { name: 'vanilla bean', category: 'pantry', typicalUnit: 'piece' },
  { name: 'gelatin', category: 'pantry', typicalUnit: 'g' },
  { name: 'corn syrup', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'molasses', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'agave syrup', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'stevia', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'powdered milk', category: 'pantry', typicalUnit: 'g' },
  { name: 'evaporated milk', category: 'pantry', typicalUnit: 'ml' },
  { name: 'sweetened condensed milk', category: 'pantry', typicalUnit: 'ml' },
  { name: 'canned corn', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned peas', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned green beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned mushrooms', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned pumpkin', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned coconut milk', category: 'pantry', typicalUnit: 'ml' },
  { name: 'canned tuna', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned salmon', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned chicken', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned black beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned kidney beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned pinto beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned chickpeas', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned white beans', category: 'pantry', typicalUnit: 'g' },
  { name: 'tomato puree', category: 'pantry', typicalUnit: 'g' },
  { name: 'marinara sauce', category: 'pantry', typicalUnit: 'g' },
  { name: 'alfredo sauce', category: 'pantry', typicalUnit: 'g' },
  { name: 'pizza sauce', category: 'pantry', typicalUnit: 'g' },
  { name: 'teriyaki sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'hoisin sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'oyster sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'stir fry sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'chili sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'sriracha', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'chili paste', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'miso paste', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'tahini', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'peanut sauce', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'sesame seeds', category: 'pantry', typicalUnit: 'g' },
  { name: 'chia seeds', category: 'pantry', typicalUnit: 'g' },
  { name: 'flax seeds', category: 'pantry', typicalUnit: 'g' },
  { name: 'sunflower seeds', category: 'pantry', typicalUnit: 'g' },
  { name: 'pumpkin seeds', category: 'pantry', typicalUnit: 'g' },
  { name: 'almonds', category: 'pantry', typicalUnit: 'g' },
  { name: 'walnuts', category: 'pantry', typicalUnit: 'g' },
  { name: 'pecans', category: 'pantry', typicalUnit: 'g' },
  { name: 'cashews', category: 'pantry', typicalUnit: 'g' },
  { name: 'pistachios', category: 'pantry', typicalUnit: 'g' },
  { name: 'hazelnuts', category: 'pantry', typicalUnit: 'g' },
  { name: 'peanuts', category: 'pantry', typicalUnit: 'g' },
  { name: 'macadamia nuts', category: 'pantry', typicalUnit: 'g' },
  { name: 'raisins', category: 'pantry', typicalUnit: 'g' },
  { name: 'dried apricots', category: 'pantry', typicalUnit: 'g' },
  { name: 'dried cranberries', category: 'pantry', typicalUnit: 'g' },
  { name: 'dried mango', category: 'pantry', typicalUnit: 'g' },
  { name: 'dried pineapple', category: 'pantry', typicalUnit: 'g' },
  { name: 'prunes', category: 'pantry', typicalUnit: 'g' },
  { name: 'granulated sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'turbinado sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'confectioners sugar', category: 'pantry', typicalUnit: 'g' },
  { name: 'instant oats', category: 'pantry', typicalUnit: 'g' },
  { name: 'rolled oats', category: 'pantry', typicalUnit: 'g' },
  { name: 'steel cut oats', category: 'pantry', typicalUnit: 'g' },
  { name: 'millet', category: 'pantry', typicalUnit: 'g' },
  { name: 'amaranth', category: 'pantry', typicalUnit: 'g' },
  { name: 'buckwheat', category: 'pantry', typicalUnit: 'g' },
  { name: 'sorghum', category: 'pantry', typicalUnit: 'g' },
  { name: 'grits', category: 'pantry', typicalUnit: 'g' },
  { name: 'polenta', category: 'pantry', typicalUnit: 'g' },
  { name: 'rice paper', category: 'pantry', typicalUnit: 'piece' },
  { name: 'panko', category: 'pantry', typicalUnit: 'g' },
  { name: 'tortilla chips', category: 'pantry', typicalUnit: 'g' },
  { name: 'pretzels', category: 'pantry', typicalUnit: 'g' },
  { name: 'croutons', category: 'pantry', typicalUnit: 'g' },
  { name: 'broth', category: 'pantry', typicalUnit: 'ml' },
  { name: 'beef broth', category: 'pantry', typicalUnit: 'ml' },
  { name: 'vegetable broth', category: 'pantry', typicalUnit: 'ml' },
  { name: 'chicken broth', category: 'pantry', typicalUnit: 'ml' },
  { name: 'curry paste', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'taco seasoning', category: 'staple', typicalUnit: 'tsp' },
  { name: 'italian seasoning', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cajun seasoning', category: 'staple', typicalUnit: 'tsp' },
  { name: 'garlic salt', category: 'staple', typicalUnit: 'tsp' },
  { name: 'onion salt', category: 'staple', typicalUnit: 'tsp' },
  { name: 'seasoning salt', category: 'staple', typicalUnit: 'tsp' },
  { name: 'herbes de provence', category: 'staple', typicalUnit: 'tsp' },
  { name: 'cumin seed', category: 'staple', typicalUnit: 'tsp' },
  { name: 'mustard seed', category: 'staple', typicalUnit: 'tsp' },
  { name: 'fennel seed', category: 'staple', typicalUnit: 'tsp' },
  { name: 'caraway seed', category: 'staple', typicalUnit: 'tsp' },
  { name: 'sesame oil', category: 'staple', typicalUnit: 'tsp' },
  { name: 'grapeseed oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'peanut oil', category: 'staple', typicalUnit: 'tbsp' },
  { name: 'chicken bouillon', category: 'staple', typicalUnit: 'tsp' },
  { name: 'beef bouillon', category: 'staple', typicalUnit: 'tsp' },
  { name: 'vegetable bouillon', category: 'staple', typicalUnit: 'tsp' },
  { name: 'pickles', category: 'perishable', typicalUnit: 'piece' },
  { name: 'sauerkraut', category: 'perishable', typicalUnit: 'g' },
  { name: 'kimchi', category: 'perishable', typicalUnit: 'g' },
  { name: 'hummus', category: 'perishable', typicalUnit: 'tbsp' },
  { name: 'tzatziki', category: 'perishable', typicalUnit: 'tbsp' },
  { name: 'pico de gallo', category: 'perishable', typicalUnit: 'tbsp' },
  { name: 'sour cream', category: 'dairy', typicalUnit: 'g' },
  { name: 'whipped cream', category: 'dairy', typicalUnit: 'g' },
  { name: 'mascarpone', category: 'dairy', typicalUnit: 'g' },
  { name: 'halloumi', category: 'dairy', typicalUnit: 'g' },
  { name: 'paneer', category: 'dairy', typicalUnit: 'g' },
  { name: 'buttermilk', category: 'dairy', typicalUnit: 'ml' },
  { name: 'cream', category: 'dairy', typicalUnit: 'ml' },
  { name: 'whipping cream', category: 'dairy', typicalUnit: 'ml' },
  { name: 'ground chicken', category: 'meat', typicalUnit: 'g' },
  { name: 'chicken tenderloin', category: 'meat', typicalUnit: 'g' },
  { name: 'turkey bacon', category: 'meat', typicalUnit: 'g' },
  { name: 'chorizo', category: 'meat', typicalUnit: 'g' },
  { name: 'pepperoni', category: 'meat', typicalUnit: 'g' },
  { name: 'salami', category: 'meat', typicalUnit: 'g' },
  { name: 'prosciutto', category: 'meat', typicalUnit: 'g' },
  { name: 'deli turkey', category: 'meat', typicalUnit: 'g' },
  { name: 'deli ham', category: 'meat', typicalUnit: 'g' },
  { name: 'ground sausage', category: 'meat', typicalUnit: 'g' },
  { name: 'meatballs', category: 'meat', typicalUnit: 'g' },
  { name: 'bologna', category: 'meat', typicalUnit: 'g' },
  { name: 'hot dogs', category: 'meat', typicalUnit: 'piece' },
  { name: 'salmon', category: 'meat', typicalUnit: 'g' },
  { name: 'tuna', category: 'meat', typicalUnit: 'g' },
  { name: 'cod', category: 'meat', typicalUnit: 'g' },
  { name: 'tilapia', category: 'meat', typicalUnit: 'g' },
  { name: 'haddock', category: 'meat', typicalUnit: 'g' },
  { name: 'halibut', category: 'meat', typicalUnit: 'g' },
  { name: 'trout', category: 'meat', typicalUnit: 'g' },
  { name: 'mahi mahi', category: 'meat', typicalUnit: 'g' },
  { name: 'crab meat', category: 'meat', typicalUnit: 'g' },
  { name: 'lobster tail', category: 'meat', typicalUnit: 'g' },
  { name: 'shrimp (frozen)', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen shrimp', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen meatballs', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen dumplings', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen burrito', category: 'frozen', typicalUnit: 'piece' },
  { name: 'frozen waffles', category: 'frozen', typicalUnit: 'piece' },
  { name: 'frozen pizza dough', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen hash browns', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen fruit mix', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen mango', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen pineapple', category: 'frozen', typicalUnit: 'g' },
  { name: 'star fruit', category: 'produce', typicalUnit: 'piece' },
  { name: 'dragon fruit', category: 'produce', typicalUnit: 'piece' },
  { name: 'jackfruit', category: 'produce', typicalUnit: 'piece' },
  { name: 'banana peppers', category: 'produce', typicalUnit: 'piece' },
  { name: 'thai basil', category: 'produce', typicalUnit: 'bunch' },
  { name: 'mint leaves', category: 'produce', typicalUnit: 'bunch' },
  { name: 'romanesco', category: 'produce', typicalUnit: 'piece' },
  { name: 'celeriac', category: 'produce', typicalUnit: 'piece' },
  { name: 'all purpose flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'bread flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'semolina flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'self rising flour', category: 'pantry', typicalUnit: 'g' },
  { name: 'pancake mix', category: 'pantry', typicalUnit: 'g' },
  { name: 'waffle mix', category: 'pantry', typicalUnit: 'g' },
  { name: 'cornbread mix', category: 'pantry', typicalUnit: 'g' },
  { name: 'cracker crumbs', category: 'pantry', typicalUnit: 'g' },
  { name: 'marshmallows', category: 'pantry', typicalUnit: 'g' },
  { name: 'peanut butter chips', category: 'pantry', typicalUnit: 'g' },
  { name: 'sprinkles', category: 'pantry', typicalUnit: 'g' },
  { name: 'active dry yeast', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'instant yeast', category: 'pantry', typicalUnit: 'tsp' },
  { name: 'ranch dressing', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'caesar dressing', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'italian dressing', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'vinaigrette', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'blue cheese dressing', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'honey mustard', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'thousand island dressing', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'relish', category: 'pantry', typicalUnit: 'tbsp' },
  { name: 'canned peaches', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned pears', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned pineapple', category: 'pantry', typicalUnit: 'g' },
  { name: 'canned fruit cocktail', category: 'pantry', typicalUnit: 'g' },
  { name: 'pork ribs', category: 'meat', typicalUnit: 'g' },
  { name: 'beef ribs', category: 'meat', typicalUnit: 'g' },
  { name: 'pork loin', category: 'meat', typicalUnit: 'g' },
  { name: 'chicken sausage', category: 'meat', typicalUnit: 'g' },
  { name: 'breakfast sausage', category: 'meat', typicalUnit: 'g' },
  { name: 'turkey pepperoni', category: 'meat', typicalUnit: 'g' },
  { name: 'frozen edamame', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen cauliflower rice', category: 'frozen', typicalUnit: 'g' },
  { name: 'frozen pizza crust', category: 'frozen', typicalUnit: 'piece' },
  { name: 'frozen pie crust', category: 'frozen', typicalUnit: 'piece' },
  { name: 'frozen puff pastry', category: 'frozen', typicalUnit: 'g' },
]

const variantGroups: VariantGroup[] = [
  {
    template: '{variant} apple',
    variants: ['gala', 'fuji', 'granny smith', 'honeycrisp', 'pink lady', 'red delicious', 'golden delicious'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} orange',
    variants: ['navel', 'blood', 'mandarin'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} grapes',
    variants: ['red', 'green', 'black'],
    category: 'produce',
    typicalUnit: 'g',
  },
  {
    template: '{variant} tomatoes',
    variants: ['cherry', 'grape', 'roma', 'heirloom'],
    category: 'produce',
    typicalUnit: 'g',
  },
  {
    template: '{variant} onion',
    variants: ['yellow', 'red', 'white', 'sweet'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} potato',
    variants: ['russet', 'yukon gold', 'red', 'fingerling'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} lettuce',
    variants: ['green leaf', 'red leaf'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} cabbage',
    variants: ['green', 'red', 'napa', 'savoy'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} mushrooms',
    variants: ['button', 'cremini', 'portobello', 'shiitake', 'oyster'],
    category: 'produce',
    typicalUnit: 'g',
  },
  {
    template: '{variant} bell pepper',
    variants: ['red', 'green', 'yellow', 'orange'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} chili pepper',
    variants: ['jalapeno', 'serrano', 'poblano', 'habanero', 'anaheim', 'thai'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} squash',
    variants: ['butternut', 'acorn', 'spaghetti', 'delicata'],
    category: 'produce',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} rice',
    variants: ['white', 'brown', 'jasmine', 'basmati', 'arborio', 'wild'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} pasta',
    variants: ['spaghetti', 'penne', 'fusilli', 'rotini', 'rigatoni', 'fettuccine', 'linguine', 'macaroni', 'orzo', 'farfalle'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} bread',
    variants: ['white', 'whole wheat', 'sourdough', 'rye', 'bagel', 'english muffin', 'baguette'],
    category: 'pantry',
    typicalUnit: 'slice',
  },
  {
    template: '{variant} tortillas',
    variants: ['flour', 'corn'],
    category: 'pantry',
    typicalUnit: 'piece',
  },
  {
    template: '{variant} beans',
    variants: ['black', 'kidney', 'pinto', 'navy', 'cannellini', 'great northern', 'garbanzo'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} lentils',
    variants: ['red', 'green', 'brown'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} split peas',
    variants: ['green', 'yellow'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} nuts',
    variants: ['almonds', 'walnuts', 'pecans', 'cashews', 'pistachios', 'hazelnuts', 'peanuts', 'macadamia'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} seeds',
    variants: ['sesame', 'chia', 'flax', 'sunflower', 'pumpkin'],
    category: 'pantry',
    typicalUnit: 'g',
  },
  {
    template: '{variant} milk',
    variants: ['whole', '2%', 'skim'],
    category: 'dairy',
    typicalUnit: 'ml',
  },
  {
    template: '{variant} yogurt',
    variants: ['plain', 'vanilla'],
    category: 'dairy',
    typicalUnit: 'g',
  },
  {
    template: '{variant} steak',
    variants: ['sirloin', 'ribeye', 'flank', 'strip'],
    category: 'meat',
    typicalUnit: 'g',
  },
  {
    template: '{variant} roast',
    variants: ['chuck', 'brisket'],
    category: 'meat',
    typicalUnit: 'g',
  },
  {
    template: '{variant} pork',
    variants: ['chops', 'tenderloin', 'shoulder', 'belly'],
    category: 'meat',
    typicalUnit: 'g',
  },
  {
    template: '{variant} chicken',
    variants: ['breast', 'thigh', 'drumstick', 'wing', 'tenderloin'],
    category: 'meat',
    typicalUnit: 'g',
  },
  {
    template: '{variant} fish',
    variants: ['cod', 'tilapia', 'salmon', 'tuna', 'halibut', 'haddock', 'trout', 'mahi mahi'],
    category: 'meat',
    typicalUnit: 'g',
  },
  {
    template: 'canned {variant} tomatoes',
    variants: ['diced', 'crushed', 'whole peeled'],
    category: 'pantry',
    typicalUnit: 'g',
  },
]

function expandVariants(groups: VariantGroup[]): IngredientSeed[] {
  const items: IngredientSeed[] = []
  for (const group of groups) {
    for (const variant of group.variants) {
      const name = group.template.replace('{variant}', variant)
      items.push({
        name,
        category: group.category,
        typicalUnit: group.typicalUnit,
      })
    }
  }
  return items
}

function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 100)
}

function buildCatalog(): IngredientSeed[] {
  const expanded = expandVariants(variantGroups)
  const combined = [...baseIngredients, ...expanded].map(item => ({
    ...item,
    name: sanitizeName(item.name),
  }))

  const seen = new Set<string>()
  const deduped: IngredientSeed[] = []

  for (const item of combined) {
    if (!item.name || item.name.includes(',')) continue
    if (seen.has(item.name)) continue
    seen.add(item.name)
    deduped.push(item)
  }

  deduped.sort((a, b) => a.name.localeCompare(b.name))
  return deduped
}

export const ingredientCatalog = buildCatalog()
export type { IngredientSeed, VariantGroup }
