import {beforeEach,describe,it,expect,vi} from 'vitest'
import type {PrismaClient} from '@prisma/client'
import type {RecipeSelection} from '../pi-meals/contracts.js'
const {state}=vi.hoisted(()=>({state:{selection:null as RecipeSelection|null}}))
vi.mock('../pi-meals/selections.js',()=>({getSelection:async()=>state.selection}))
import {createBasket,prepareBasket,fillBasket,getBasket,reconcileBasket} from '../pi-meals/baskets.js'
function database(){
 const docs=new Map<string,any>(),ops=new Map<string,any>()
 const db:any={piMealDocument:{findUnique:async({where}:any)=>docs.get(where.id)??null,create:async({data}:any)=>{docs.set(data.id,data);return data},updateMany:async({where,data}:any)=>{const row=docs.get(where.id);if(!row||row.revision!==where.revision)return {count:0};docs.set(where.id,{...row,...data});return {count:1}}},piMealOperation:{findUnique:async({where}:any)=>ops.get(where.id)??null,create:async({data}:any)=>{ops.set(data.id,structuredClone(data));return data},update:async({where,data}:any)=>{ops.set(where.id,{...ops.get(where.id),...structuredClone(data)})}},$transaction:async(fn:any)=>fn(db)}
 return db as PrismaClient
}
const observed=(items:Array<{productId:string;quantity:number}>)=>({verified:true as const,items,evidence:{source:'test'}})
async function ready(prisma:PrismaClient,executor:'ocado'|'aside'='ocado'){
 const basket=await createBasket(prisma,'actor',{operationId:'create',selectionId:'s',executor})
 return prepareBasket(prisma,basket.id,'actor',{operationId:'prepare',expectedRevision:basket.revision,lines:[{id:'a',name:'Flour',quantity:800,unit:'g',productId:'12345',productName:'Flour',packQuantity:500,packUnit:'g'}]})
}
beforeEach(()=>{state.selection={id:'s',revision:1,title:'Dinner',items:[],stock:[],updatedAt:'now',lines:[{id:'a',name:'Flour',quantity:800,unit:'g',buyQuantity:800,haveQuantity:0,sources:[],warnings:[]}]}})
describe('basket effects',()=>{
 it('records full readback and replays the same receipt without a second mutation',async()=>{const db=database(),basket=await ready(db),input={operationId:'fill',expectedRevision:basket.revision,selectionRevision:1};let packs=1;const addPacks=vi.fn(async(_id:string,n:number)=>{packs+=n});const deps={mutationsEnabled:true,executor:{readCart:async()=>observed([{productId:'manual',quantity:4},{productId:'12345',quantity:packs}]),addPacks}};const result=await fillBasket(db,basket.id,'actor',input,deps);expect(result.status).toBe('complete');expect((result.receipt as any).after.items).toContainEqual({productId:'manual',quantity:4});expect(await fillBasket(db,basket.id,'actor',input,deps)).toEqual(result);expect(addPacks).toHaveBeenCalledTimes(1);expect(addPacks).toHaveBeenCalledWith('12345',2)})
 it('stale approval never calls the executor',async()=>{const db=database(),basket=await ready(db);state.selection!.revision=2;const addPacks=vi.fn();await expect(fillBasket(db,basket.id,'actor',{operationId:'fill',expectedRevision:basket.revision,selectionRevision:1},{mutationsEnabled:true,executor:{readCart:async()=>observed([]),addPacks}})).rejects.toThrow('selection changed');expect(addPacks).not.toHaveBeenCalled()})
 it('unknown reads never become empty baselines or writes',async()=>{const db=database(),basket=await ready(db),addPacks=vi.fn();const result=await fillBasket(db,basket.id,'actor',{operationId:'fill',expectedRevision:basket.revision,selectionRevision:1},{mutationsEnabled:true,executor:{readCart:async()=>{throw new Error('unknown cart')},addPacks}});expect(result.status).toBe('needs_review');expect((result.receipt as any).baseline).toBeUndefined();expect(addPacks).not.toHaveBeenCalled()})
 it('persists uncertain intent and never replays an interrupted write',async()=>{const db=database(),basket=await ready(db),input={operationId:'fill',expectedRevision:basket.revision,selectionRevision:1},addPacks=vi.fn(async()=>{throw new Error('connection lost after click')});const deps={mutationsEnabled:true,executor:{readCart:async()=>observed([{productId:'manual',quantity:3}]),addPacks}};const result=await fillBasket(db,basket.id,'actor',input,deps);expect(result.status).toBe('needs_review');expect((result.receipt as any).uncertain).toBe(true);expect((result.receipt as any).intent.targetQuantity).toBe(2);expect(await fillBasket(db,basket.id,'actor',input,deps)).toEqual(result);expect(addPacks).toHaveBeenCalledTimes(1);expect((await getBasket(db,basket.id))?.executor).toBe('ocado');const reconciled=await reconcileBasket(db,basket.id,'actor',{operationId:'reconcile',expectedRevision:result.revision},deps);expect(reconciled.status).toBe('needs_review');expect(addPacks).toHaveBeenCalledTimes(1)})
 it('keeps one Aside task identity on duplicate fill without launching a browser',async()=>{const db=database(),basket=await ready(db,'aside'),input={operationId:'fill',expectedRevision:basket.revision,selectionRevision:1};const result=await fillBasket(db,basket.id,'actor',input);expect(result.status).toBe('needs_review');expect((await fillBasket(db,basket.id,'actor',input)).taskId).toBe(result.taskId)})
})
